### ISSUE TITLE
No directory `MoleculeFiles` in `SAMPL6/host_guest/`

### ISSUE THREAD

**Issue by slochower** [MobleyLab/SAMPL6#1]
The file [SAMPL6/host_guest/CB8AndGuests/README.md](https://github.com/MobleyLab/SAMPL6/blob/94fde1c43a38df6085c73bf2d493b5f55aec20d3/host_guest/CB8AndGuests/README.md) says:

> The other files were generated by the OpenEye toolkits using the Jupyter notebook provided in "../MoleculeFiles"

(Same thing for `SAMPL6/host_guest/OctaAcidsAndGuests/README.md`)

I don't see that directory, but I think you may mean the notebook `GenerateInputs.ipynb` in `../` (i.e., [SAMPL6/host_guest/GenerateInputs.ipynb](https://github.com/MobleyLab/SAMPL6/blob/94fde1c43a38df6085c73bf2d493b5f55aec20d3/host_guest/GenerateInputs.ipynb)) . I'm leaving a note here in case other people are looking for the directory.

**Comment by davidlmobley** [comment]
Thanks, yes. I was originally working on this in a separate folder and reorganized slightly when I migrated to GitHub; I forgot to change the documentation when I did so. Possibly I also have a similar path problem in my Jupyter notebook. You're correct, it means `../` in this case. I'll do a PR to fix this sometime soon.

**Comment by davidlmobley** [comment]
Closed via #2
