### ISSUE TITLE
Physical properties

### ISSUE THREAD

**Issue by Steboss** [MobleyLab/SAMPL6#13]
Hi everbody,

I was wondering if there are any news about the physical properties part of the SAMPL and if they will be released soon. 
Thank you very much

Stefano

**Comment by davidlmobley** [comment]
Yes. It's becoming a pKa challenge and we're deferring the logD component. I will either have files up for this this week and send an e-mail (though some notes on it are now in #11 ) OR I will send an e-mail to everyone who is signed up on the D3R SAMPL6 list with an estimate of when files will be up. (Please sign up there!) 

cc @MehtapIsik and @jchodera

**Comment by Steboss** [comment]
All right, 

Thanks very much @davidlmobley

**Comment by davidlmobley** [comment]
Marking as closed
