### ISSUE TITLE
Loading up SAMPLing files converted to other formats.

### ISSUE THREAD

**Issue by mrshirts** [MobleyLab/SAMPL6#19]
Finally getting around to this.  I think that I want to load up all the converted files in the same directories as the AMBER/GROMACS/OpenMM, and just do it like that.  I'll have energy comparisons between all fies.

One problem that I am getting is that AMBER->GROMACS->AMBER no longer matches. Seems to be something in ParmEd (I think), so I am tracking that down.  They are pretty similar in energies, but there are differences in the files that I think would be useful to track down.

What is the timing here to get this sorted out and the files uploaded?

**Comment by davidlmobley** [comment]
Probably in the next couple of weeks would be good. Sooner if someone comes along and asks for the files, but no one has been asking for them yet.

**Comment by mrshirts** [comment]
OK, my student wants to start some runs, so soon after thanksgiving.

**Comment by andrrizzi** [comment]
@mrshirts a heads up that I may have to regenerate the files in the `Reference/` folder with a different ionic strength (the ones in `SAMPLing/` won't be changed). They should be up tomorrow or in two days. I'll ping you again once I figure it out.

**Comment by davidlmobley** [comment]
@mrshirts - anything you need for this?

**Comment by davidlmobley** [comment]
Resolved via #30
