### ISSUE TITLE
Correct CB8  buffer concentration

### ISSUE THREAD

**Issue by Steboss** [MobleyLab/SAMPL6#23]
Hi everybody,

I just noticed that there is a misleading instruction in the host-guest challenge.
In this [image](https://github.com/MobleyLab/SAMPL6/blob/master/images/CB8_guests.jpg) the indication about the sodium phosphate buffer for CB8 system is 20 mM. However, on the official website [page](https://drugdesigndata.org/about/sampl6/cb8) the sodium phosphate is 25 mM.
Thus, I would like to know which is the correct buffer concentration.
Thank you very much,

Stefano

**Comment by davidlmobley** [comment]
@andrrizzi do you know off the top of your head? Otherwise I'll have to refresh my memory today.

**Comment by andrrizzi** [comment]
Hi @Steboss . I think the 20mM was a typo, and the correct phosphate buffer is 25mM. It was corrected it in the main text in 51104d3, but the figure was probably not updated.

**Comment by Steboss** [comment]
Oh great,
Thanks @andrrizzi and @davidlmobley

**Comment by davidlmobley** [comment]
Ah, yes, that's exactly right. I need to update the figure.
