### ISSUE TITLE
SAMPLing deadline?

### ISSUE THREAD

**Issue by jmichel80** [MobleyLab/SAMPL6#31]
Dear organisers, 

Is there any room to delay our SAMPLing submissions by one week? If not we are going to mis the deadline by a couple of days for this subset of SAMPL6 activities, but should have submission for the rest. 

Best wishes,

Julien

**Comment by davidlmobley** [comment]
Yes! We're expecting to get out an announcement today to this effect. There were delays in getting the automated submission handling in place so we're anticipating delaying all deadlines until next week.

**Comment by michalispapadourakis** [comment]
Dear organisers,

I have uploaded the data in the challenge for the octa-acids section. It send me a notification that everything was submitted well and evaluation awaits. but I cannot see the files in the section <<manage your data>>(It has also a message "OA_buffer_ModelA_1.txt is missing integer value in filename.") 

Kind regards,

MIchail

**Comment by michalispapadourakis** [comment]
Dear organisers, 

I have uploaded the data in the challenge for the octa-acids section. It send me a notification that everything was submitted well and evaluation awaits but I cannot see the files in the section <manage your data>. When I tried to submit one file at a time there was a message: "OA_buffer_ModelA_1.txt is missing integer value in filename." 

Kind regards,

MIchail

**Comment by iorga** [comment]
Your file name should be in the form OA-bufferModelA-1.txt, see https://github.com/MobleyLab/SAMPL6/blob/pKa/host_guest_instructions.md#uploading-your-predictions for detailed instructions. I had the same problem at the beginning.

Best regards,
Bogdan

**Comment by michalispapadourakis** [comment]
Thanks for the answer.

Kind regards,

Michail

**Comment by davidlmobley** [comment]
@jmichel80 - e-mail went out announcing deadline delay. 

@iorga - thanks for clarifying that. :)
