### ISSUE TITLE
pKa predictions upload

### ISSUE THREAD

**Issue by iorga** [MobleyLab/SAMPL6#40]
Hello,

I'm trying to submit pKa predictions (e.g. `typeI-Iorga-2.csv`)  and I get the error `typeI-Iorga-2.csv does not have in the filename`. I get the same error with typeI, typeII and typeIII files, -1 or -2, and also with the .txt extension.

Files with the same naming rules and very similar content were correctly uploaded about two weeks ago.

Any help would be appreciated.

Best regards,
Bogdan

**Comment by MehtapIsik** [comment]
Hello,

We have just managed to fix this issue in submission system for pKa predictions. Could you please refresh the D3R page and try again with using submission files with .csv extension?

Please let us know if the problem persists.

Best regards,
Mehtap

**Comment by iorga** [comment]
It works fine now. I close the issue. Thanks.
