### ISSUE TITLE
logP submission issue

### ISSUE THREAD

**Issue by hjuinj** [MobleyLab/SAMPL6#71]
Hi,

I am trying to submit my logP prediction via the D3R portal but after I hit `start upload` I get:
`logP-NameString-1.csv does not have in the filename`. Although after each upload I get a notification saying upload is successful, I still see `No submissions yet` under the `Manage Your Data` section.

It seems a similar problem was raised for the pKa challenge.

**Comment by MehtapIsik** [comment]
@hjuinj Could you please try uploading your files again? I tried to upload your submission files (`logP-Wang_Riniker-1.csv`, `logP-Wang_Riniker-2.csv`, and `logP-Wang_Riniker-3.csv`) using my account and I haven't observed any problems.

**Comment by hjuinj** [comment]
Hi Mehtap, 

I actually resubmitted my solutions on Friday and the issue disappeared. And I can see my submissions under the `Manage Your Data` section even after logging out and back in again (by this stage I have completed the submission procedure right?)

Sorry I forgot to close this issue and thanks for your help.
